---
title: "Literature Review and Expectations"
---

:::{.callout-important}
Due Friday, March 20, at 11:59 pm on Canvas
:::

## Purpose

The goal of this assignment is to help you integrate various pieces of research. This involves summarizing, finding connections between articles, and identifying key limitations in existing work. As you move toward the final paper, it is important to develop a theory and hypotheses (i.e., an explanation and expectations).


## Task

Write a 3- to 5-page literature review on your research topic (12-point font, double-spaced, 1-inch margins).

A literature review is a piece of writing that summarizes existing academic research on a given topic. It is, however, not a collection of summaries about each article (that would be an annotated bibliography). Instead, a literature review conveys what these works say together and identifies gaps in the literature. In other words, it shows what we know about something but also highlights what we don't yet know.


After the literature review, you should explain your expectations and justify. Write down explicit hypotheses and make sure you offer a theoretical rationale for them. (Title this section ``Expectations’’.)



## Criteria for Success

A successful submission will:

1. Use strong and clear topic sentences to convey the key points.
2. Have a coherent structure (e.g., address what we know before moving on to the limitations)
3. Identify limitations of existing work (e.g., is the data too old? Are existing theories missing something important? Are the measures not appropriate for the question?)


## Guide to Writing a Literature Review

Check out this [guide on writing a literature review in political science](https://guides.library.ucsc.edu/write-a-literature-review).

