---
title: "Problem Set 7"
---

:::{.callout-important}
Due November 8 at 11:59 pm on Canvas
:::

Problem Set 7 is posted on Canvas. You must use the provided RMarkdown file to complete this problem set.

- Use the RMarkdown file provided (.Rmd extension) and write your answers and code in the spaces provided. Submit the PDF that is "knitted" (1 file).^[This route requires a few more tools. You need to install [RMarkdown](https://rmarkdown.rstudio.com/lesson-1.html) and [TinyTeX](https://yihui.org/tinytex/). The upside? You can produce beautiful documents that show your code and output.]

If you have any issues using RMarkdown please see me in my office so we can make sure you can knit the file on your computer.

### Files

1. [Problem Set - PDF](https://agnesscott.instructure.com/files/761094/download?download_frd=1)
2. [RMardown file](https://agnesscott.instructure.com/files/608143/download?download_frd=1)
3. [PDF of study to complete the problem set](/data/aspr1994_pset7.pdf)



## Purpose

This problem set will help you practice:

1. Determining whether a study uses experimental or observational data
2. Identify the average treatment effect in a study
3. Assess the internal and external validity of a study




## Criteria for success

In addition to providing the correct code and/or answer, a successful problem set will:

1. Have clear explanations that demonstrate your knowledge of the material
