---
title: "Problem Set 5"
---

:::{.callout-important}
Due Friday, April 10, at 11:59 pm on Canvas
:::


Use the RMarkdown file provided (.Rmd extension) and write your answers and code in the spaces provided. Submit the PDF that is "knitted."

### Files

1. [Problem Set - PDF](https://hc.instructure.com/files/2852927/download?download_frd=1)
2. [RMardown file](https://hc.instructure.com/files/2852928/download?download_frd=1)
3. [PDF of study to complete the problem set](https://hc.instructure.com/files/2852926/download?download_frd=1)



## Purpose

This fourth problem set will help you practice:

1. Understanding the components of a linear regression model
2. Running a linear regression model in R
3. Interpreting the output of the lm() function
4. Determining whether a study uses experimental or observational data
5. Identify the average treatment effect in a study
6. Assess the internal and external validity of a study



## Criteria for success

In addition to providing the correct code and/or answer, a successful problem set will:

1. Have clear explanations that demonstrate your knowledge of the material
2. Use the "comment out" function to explain what the code is doing



